version: 0.2

env:
  variables:
    TF_VERSION: "1.14.9"
    # Default environment if not set by the pipeline
    ENVIRONMENT: "staging"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Terraform..."
      - curl -s -qL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip -d /usr/local/bin
      - terraform version
      - echo "Installing tfsec..."
      - curl -s -qL https://github.com/aquasecurity/tfsec/releases/download/v1.28.1/tfsec-linux-amd64 -o tfsec
      - chmod +x tfsec
      - mv tfsec /usr/local/bin/

  pre_build:
    commands:
      - echo "Running Infrastructure Checks..."
      - cd infra
      - terraform fmt -check -recursive
      - terraform init -input=false -backend-config="key=${ENVIRONMENT}/terraform.tfstate"
      - terraform validate
      - tfsec .

  build:
    commands:
      - echo "Running Terraform Plan for ${ENVIRONMENT}..."
      - terraform plan -out=tfplan -input=false -var="Environment=${ENVIRONMENT}"
      
      - echo "Applying Infrastructure Changes..."
      - terraform apply -input=false -auto-approve tfplan

  post_build:
    commands:
      - echo "Infrastructure deployment completed on $(date)"
      - terraform output -json > tf_outputs.json

artifacts:
  files:
    - tf_outputs.json
    - tfplan
  name: infra-build-artifacts