openapi: 3.0.1
info:
  title: e-commarce-shop-api
  description: REST API Gateway for e-commarce-shop
  version: 1.0.0

paths:
%{ for path, methods in { for route in routes : route.path => route... } }
  ${path}:
%{ for route in methods }
    ${lower(route.method)}:
      summary: API Endpoint for ${path} (${route.method})
%{ if length(regexall("\\{([^}]+)\\}", path)) > 0 }
      parameters:
%{ for match in regexall("\\{([^}]+)\\}", path) }
        - name: ${match[0]}
          in: path
          required: true
          schema:
            type: string
%{ endfor }
%{ endif }
      responses:
        "200":
          description: OK
%{ if try(!route.config.no_auth, true) }
      security:
        - custom_lambda_auth: []
%{ endif }
      x-required-groups: ${jsonencode(route.config.permissions)}
      x-amazon-apigateway-integration:
        uri: ${route.config.lambda}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000
%{ endfor }
    options:
      summary: CORS preflight for ${path}
%{ if length(regexall("\\{([^}]+)\\}", path)) > 0 }
      parameters:
%{ for match in regexall("\\{([^}]+)\\}", path) }
        - name: ${match[0]}
          in: path
          required: true
          schema:
            type: string
%{ endfor }
%{ endif }
      responses:
        "200":
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      security: []
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,x-api-key'"
            responseTemplates:
              application/json: '{}'
%{ endfor }

security:
  - api_key: []

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
    custom_lambda_auth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: "authorizer"
      x-amazon-apigateway-authorizer:
        authorizerUri: ${authorizer_lambda_invoke_arn}
        authorizerResultTtlInSeconds: 300
        type: token