openapi: 3.0.1
info:
  title: e-commarce-shop-api
  description: REST API Gateway for e-commarce-shop
  version: 1.0.0

paths:
  /upload-product:
    post:
      summary: Upload a new product
      responses:
        "200":
          description: OK
      security:
        - custom_lambda_auth: [] 
      x-required-groups: ["admin"]
      x-amazon-apigateway-integration:
        uri: ${upload_product_lambda_uri}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000
  /update-product/{productId}:
    patch:
      summary: Update an existing product
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
      security:
        - custom_lambda_auth: []
      x-required-groups: ["admin"]
      x-amazon-apigateway-integration:
        uri: ${update_product_lambda_uri}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000
  /get-products-for-category/{category}:
    get:
      summary: Get products for a category
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
      security:
        - custom_lambda_auth: [] 
      x-amazon-apigateway-integration:
        uri: ${get_products_for_category_lambda_uri}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000
  /add-to-cart:
    post:
      summary: Add a new product to cart
      responses:
        "200":
          description: OK
      security:
        - custom_lambda_auth: [] 
      x-required-groups: []
      x-amazon-apigateway-integration:
        uri: ${add_to_cart_lambda_uri}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000
  /create-coupon:
    post:
      summary: Create a new coupon
      responses:
        "200":
          description: OK
      security:
        - custom_lambda_auth: [] 
      x-required-groups: ["admin"]
      x-amazon-apigateway-integration:
        uri: ${create_coupon_lambda_uri}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000

components:
  securitySchemes:
    custom_lambda_auth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: "authorizer"
      x-amazon-apigateway-authorizer:
        authorizerUri: ${authorizer_lambda_invoke_arn}
        authorizerResultTtlInSeconds: 300
        type: token