openapi: 3.0.1
info:
  title: e-commarce-shop-api
  description: HTTP API Gateway for e-commarce-shop
  version: 1.0.0

paths:
  /upload-product:
    post:
      summary: Upload a new product
      responses:
        "200":
          description: OK
      security:
        - cognito: []
      x-amazon-apigateway-integration:
        uri: ${upload_product_lambda_uri}
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 12000

components:
  securitySchemes:
    cognito:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerArns:
          - ${cognito_user_pool_arn}
